### ISSUE TITLE
Question about "ds.getAddress(uint8_t *address)" , how to use to detect a missing sensor?

### ISSUE THREAD

**Issue by AGuzman76** [matmunk/DS18B20#16]
Hello there!

Does anyone know the best way to detect when a sensor has been disconnected?  (i.e. wire is cut)

I was hoping to use the "ds.getAddress" function, but I can't get any valid data on this.
Note:  the sensor is working fine.  I can pull both degrees F and C without issues.  only using 1 sensor.

I've tried other functions like:  ds.getPowerMode, but after the system is running if I just pull the wire connection, nothing changes, the "ds.getPowerMode" keeps outputting the same value.  same for any of the "ds.get..." functions, none change. 

Is there data stored in the variables from the OneWire.h that it's not possible to reset if the DS18B20 sensor is disconnected?

Thank you!

**Comment by matmunk** [comment]
Hi,

I think you need to periodically check for the existence of the sensor. Have you tried using ds.selectNext()?
