### ISSUE TITLE
Device not found!

### ISSUE THREAD

**Issue by montyx99** [matmunk/DS18B20#3]
Hello,
I've tried to use this library with my DS18B20 sensor and a NodeMCU v1.
The circuit is very simple, the DS18B20 GND>GND, Data & Vin > 4K7 Resistor, Data>D4, Vin>3v3.
I use the full code of the [Examples/Simple](https://github.com/matmunk/DS18B20/blob/master/examples/Single/Single.ino). There is an address, which is not documented:
uint8_t address[] = {40, 250, 31, 218, 4, 0, 0, 52};

Since I use this example, I've got the following exception:
14:17:44.292 -> Device not found!

The device is not recognized on the given address, and there is not any clue in both of your code, or in the documentation. What can I do? How can I figure out the address of my sensor?

Thanks in advance,
Montyx

**Comment by matmunk** [comment]
Hi @montyx99 

That address is hardcoded from one of my own devices, if I remember correctly. Please try the other example, "Multiple", which will automatically detect any devices present on the bus and print their addresses (which you can then use in the first example).
