### ISSUE TITLE
does it support parasitic power?

### ISSUE THREAD

**Issue by youxiaojie** [matmunk/DS18B20#9]
does it support parasitic power?

**Comment by matmunk** [comment]
Hi @youxiaojie

Yes, it detects the power mode automatically. It even supports mixing devices with different power modes.

**Comment by youxiaojie** [comment]
1.if different type of sensors, 1822 18b20 18s20 in the same line, is it ok?
2. 3 sensors in system, so It will initialize 3 instances from class and get temp then print it. the question is how do I which one represent which component? and if I remove one, how the program do? eg, I hope to show:points1:23C point2 25C point3 28C for 3 sensors, if the middle sensors is removed, I hope to show:points1:23C point2 NC point3 28C. could you give me some advice.

**Comment by matmunk** [comment]
Yes, I believe that should work fine. Please let me know if you encounter any problems.
